### ISSUE TITLE
Table style attribute is not working as expected

### ISSUE THREAD

**Issue by SergiiMarkin** [danomatic/react-pdf-html#13]
1. I am going to display the below html string from the CKEditor 5 in @react-pdf/renderer Document.
**<style>
            .table {
                margin: .9em auto;
                display: table;
            }
            .table table {
              border-collapse: collapse;
              border-spacing: 0;
              width: 100%;
              height: 100%;
              border: 1px double #b3b3b3;
            }
            .table table td, .ck-content .table table th {
                min-width: 2em;
                padding: .4em;
                border: 1px solid #bfbfbf;
            }
  </style>
<div class="table" style="height:30px;width:500px;"><table><tbody>********************</tbody></table></div>

2. Here is the screenshot from current broken table.
![BrokenTable](https://user-images.githubusercontent.com/85687049/134734648-779a2e21-54c6-40ea-bf53-d2ce2626e680.png)

3. Here is expected table look.
![expectedTable](https://user-images.githubusercontent.com/85687049/134734808-1f16fbd7-9314-463f-bbb8-638f1290ccdb.png)

4. My Question is
How can I display the table properly as expected?

Thanks in advance!

**Comment by danomatic** [comment]
React-pdf doesn’t actually have a table element so I’m doing my best to translate the table into its flex-based layout. I think the major thing that’s that’s failing here is the height:100%. It’s collapsing all the height down to the padding so that height needs to be relative to a parent element with height, or you should set an explicit height for the cells or table.
