### ISSUE TITLE
how pass react-pdf attributtes to the components

### ISSUE THREAD

**Issue by JuanDiegoGV** [danomatic/react-pdf-html#61]
Hi, first thank you for create this package.
I read how work the package and if i understand, this package converts html tags like <span> and <p> to the react-pdf component <Text>.
My question is how to pass the react-pdf attributes directly to the converted component, for example:
I want to pass hyphenationCallback attribute to all the <Text> components that the package returns.

**Comment by danomatic** [comment]
Hi @JuanDiegoGV. Thank you for your question. Because this package only converts html strings to `react-pdf` components, it doesn't have a full `react-dom` setup with jsx attributes. In theory, someone could create a `react-pdf-dom` type of package that directly converts from `react-dom` JSX to `react-pdf` and passes along callback attributes, but I haven't taken that on at this time and it doesn't seem as useful because `react-pdf` can already be written in JSX.
